---
title: "Performance evaluation of raspir"
author: "Marie-Madlen Pust"
date: "28 11 2020"
output: html_document
---

```{r setup, include=FALSE}
# Load packages
library("readr")
library("ggplot2")
library("ggpubr")
library("pheatmap")
library("tidyverse")
library("grid")
library("ggplotify")
library("rcompanion")
```

```{r}
# Define functions
make_bold_names <- function(mat, rc_fun, rc_names) {
  newnames <- rc_fun(mat)
  bold_names <- lapply(newnames, function(x) bquote(italic(.(x))))
  
  ids <- rc_names %>% match(rc_fun(mat))
  ids %>%
    walk(
      function(i)
        bold_names[i] <<-
        bquote(bolditalic(.(rc_fun(mat)[i]))) %>%
        as.expression()
    )
  as.expression(bold_names)
}

set_base_size = 9
```

```{r setup, include=FALSE}
# Import table (first figure)
makeHeatmap_222 <- read_delim("exampleRun_mockCommunity_seed222.csv", ";", 
                              escape_double = FALSE, trim_ws = TRUE)
makeHeatmap_222 <- data.frame(makeHeatmap_222)
rownames(makeHeatmap_222) <- makeHeatmap_222$Species
makeHeatmap_222$Species <- NULL

# Import table (second figure)
stats02 <- read_delim("raspir_run_statistics.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
stats02 <- data.frame(stats02)

```

```{r}

theHeatmap <-
  pheatmap(as.matrix(makeHeatmap_222),
         cluster_rows = FALSE, 
         cluster_cols = FALSE,
         border_color = "black",
         labels_row = make_bold_names(as.matrix(makeHeatmap_222), rownames,
                                      c("Rothia mucilaginosa", 
                                        "Pseudomonas aeruginosa",
                                        "Streptococcus salivarius", 
                                        "Streptococcus pneumoniae",
                                        "Streptococcus mitis", 
                                        "Streptococcus thermophilus",
                                        "Streptococcus equinus", 
                                        "Staphylococcus aureus",
                                        "Eubacterium sulci", 
                                        "Escherichia coli")),
         gaps_col = 8, 
         legend = FALSE, 
         color = c("white", 
                   "palegreen2", 
                   "orange", 
                   "forestgreen"), 
         angle_col = 0, 
         cellwidth = 30,
         fontsize = 12,
         labels_col = c("30", "50", "70", "100", 
                        "200", "300", "400", "500",
                        "30", "50", "70", "100", 
                        "200", "300", "400", "500"))

theHeatmap_gg <-
  as.ggplot(theHeatmap, scale=0.95) +
  geom_label(aes(x=0.2, y = 0.96, 
                 label = " with raspir "), fill="white", size=4.5) +
  geom_label(aes(x=0.5, y = 0.96, 
                 label = " without raspir "), fill="white", size=4.5) +
  geom_text(aes(x=0.4, y=0.04, 
                label = "Number of short reads (rare species)"), size=4.5)

#ggsave("Figure01.pdf",
 #      plot=theHeatmap_gg,
  #     device = "pdf",
   #    width = 9.95,
    #   height = 8.71,
     #  dpi = 600,
      # scale = 1)

```


```{r}

# Sensitivity ####
stats02_30 <- 
  subset(stats02, Count == 30)
sens30_raspir_median = median(stats02_30$Sensitivity_raspir)
sens30_raspir_min = min(stats02_30$Sensitivity_raspir)
sens30_raspir_max = max(stats02_30$Sensitivity_raspir)
  
sens30_normal_median = median(stats02_30$Sensitivity_normal)
sens30_normal_min = min(stats02_30$Sensitivity_normal)
sens30_normal_max = max(stats02_30$Sensitivity_normal)

stats02_100 <- 
  subset(stats02, Count == 100)
sens100_raspir_median = median(stats02_100$Sensitivity_raspir)
sens100_raspir_min = min(stats02_100$Sensitivity_raspir)
sens100_raspir_max = max(stats02_100$Sensitivity_raspir)
  
sens100_normal_median = median(stats02_100$Sensitivity_normal)
sens100_normal_min = min(stats02_100$Sensitivity_normal)
sens100_normal_max = max(stats02_100$Sensitivity_normal)

stats02_200 <- 
  subset(stats02, Count == 200)
sens200_raspir_median = median(stats02_200$Sensitivity_raspir)
sens200_raspir_min = min(stats02_200$Sensitivity_raspir)
sens200_raspir_max = max(stats02_200$Sensitivity_raspir)
  
sens200_normal_median = median(stats02_200$Sensitivity_normal)
sens200_normal_min = min(stats02_200$Sensitivity_normal)
sens200_normal_max = max(stats02_200$Sensitivity_normal)

stats02_300 <- 
  subset(stats02, Count == 300)
sens300_raspir_median = median(stats02_300$Sensitivity_raspir)
sens300_raspir_min = min(stats02_300$Sensitivity_raspir)
sens300_raspir_max = max(stats02_300$Sensitivity_raspir)
  
sens300_normal_median = median(stats02_300$Sensitivity_normal)
sens300_normal_min = min(stats02_300$Sensitivity_normal)
sens300_normal_max = max(stats02_300$Sensitivity_normal)

stats02_400 <- 
  subset(stats02, Count == 400)
sens400_raspir_median = median(stats02_400$Sensitivity_raspir)
sens400_raspir_min = min(stats02_400$Sensitivity_raspir)
sens400_raspir_max = max(stats02_400$Sensitivity_raspir)
  
sens400_normal_median = median(stats02_400$Sensitivity_normal)
sens400_normal_min = min(stats02_400$Sensitivity_normal)
sens400_normal_max = max(stats02_400$Sensitivity_normal)

sens_raspir_median <-
  c(sens30_raspir_median, 
        sens100_raspir_median,
        sens200_raspir_median,
        sens300_raspir_median,
        sens400_raspir_median)

sens_raspir_min <-
  c(sens30_raspir_min,
        sens100_raspir_min,
        sens200_raspir_min,
        sens300_raspir_min,
        sens400_raspir_min)

sens_raspir_max <-
  c(sens30_raspir_max,
        sens100_raspir_max,
        sens200_raspir_max,
        sens300_raspir_max,
        sens400_raspir_max)

sens_normal_median <-
  c(sens30_normal_median, 
        sens100_normal_median,
        sens200_normal_median,
        sens300_normal_median,
        sens400_normal_median)

sens_normal_min <-
  c(sens30_normal_min,
        sens100_normal_min,
        sens200_normal_min,
        sens300_normal_min,
        sens400_normal_min)

sens_normal_max <-
  c(sens30_normal_max,
        sens100_normal_max,
        sens200_normal_max,
        sens300_normal_max,
        sens400_normal_max)

cCount <- c(30, 100, 200, 300, 400)

sens_data <- 
  as.data.frame(cbind(cCount,
                      sens_raspir_median, 
                      sens_raspir_max,
                      sens_raspir_min, sens_normal_median,
                      sens_normal_max, sens_normal_min))



sens_plot <-
  ggplot(data=sens_data) +
  geom_pointrange(aes(x=cCount, 
                      y=sens_raspir_median, 
                      ymin=sens_raspir_min,
                      ymax=sens_raspir_max), color="red") +
  geom_line(aes(x=cCount, y=sens_raspir_median), color="red", size=1.3, alpha=0.5) +
  geom_pointrange(aes(x=cCount, 
                      y=sens_normal_median,
                      ymin=sens_normal_min,
                      ymax=sens_normal_max),
                  color="black") +
  geom_line(aes(x=cCount, y=sens_normal_median), color="black", size=1.3, alpha=0.5) +
  ylab("Sensitivity   ") +
  ylim(-2,102) +
  xlab(" ") +
  theme_pubr(border=TRUE, base_size = set_base_size) +
  theme(axis.text.x = element_blank())

```


```{r}
# Specificity ###
spec30_raspir_median = median(stats02_30$Specificity_raspir)
spec30_raspir_min = min(stats02_30$Specificity_raspir)
spec30_raspir_max = max(stats02_30$Specificity_raspir)
  
spec30_normal_median = median(stats02_30$Specificity_normal)
spec30_normal_min = min(stats02_30$Specificity_normal)
spec30_normal_max = max(stats02_30$Specificity_normal)


spec100_raspir_median = median(stats02_100$Specificity_raspir)
spec100_raspir_min = min(stats02_100$Specificity_raspir)
spec100_raspir_max = max(stats02_100$Specificity_raspir)
  
spec100_normal_median = median(stats02_100$Specificity_normal)
spec100_normal_min = min(stats02_100$Specificity_normal)
spec100_normal_max = max(stats02_100$Specificity_normal)

spec200_raspir_median = median(stats02_200$Specificity_raspir)
spec200_raspir_min = min(stats02_200$Specificity_raspir)
spec200_raspir_max = max(stats02_200$Specificity_raspir)
  
spec200_normal_median = median(stats02_200$Specificity_normal)
spec200_normal_min = min(stats02_200$Specificity_normal)
spec200_normal_max = max(stats02_200$Specificity_normal)

spec300_raspir_median = median(stats02_300$Specificity_raspir)
spec300_raspir_min = min(stats02_300$Specificity_raspir)
spec300_raspir_max = max(stats02_300$Specificity_raspir)
  
spec300_normal_median = median(stats02_300$Specificity_normal)
spec300_normal_min = min(stats02_300$Specificity_normal)
spec300_normal_max = max(stats02_300$Specificity_normal)

spec400_raspir_median = median(stats02_400$Specificity_raspir)
spec400_raspir_min = min(stats02_400$Specificity_raspir)
spec400_raspir_max = max(stats02_400$Specificity_raspir)
  
spec400_normal_median = median(stats02_400$Specificity_normal)
spec400_normal_min = min(stats02_400$Specificity_normal)
spec400_normal_max = max(stats02_400$Specificity_normal)

spec_raspir_median <-
  c(spec30_raspir_median, 
        spec100_raspir_median,
        spec200_raspir_median,
        spec300_raspir_median,
        spec400_raspir_median)

spec_raspir_min <-
  c(spec30_raspir_min,
        spec100_raspir_min,
        spec200_raspir_min,
        spec300_raspir_min,
        spec400_raspir_min)

spec_raspir_max <-
  c(spec30_raspir_max,
        spec100_raspir_max,
        spec200_raspir_max,
        spec300_raspir_max,
        spec400_raspir_max)

spec_normal_median <-
  c(spec30_normal_median, 
        spec100_normal_median,
        spec200_normal_median,
        spec300_normal_median,
        spec400_normal_median)

spec_normal_min <-
  c(spec30_normal_min,
        spec100_normal_min,
        spec200_normal_min,
        spec300_normal_min,
        spec400_normal_min)

spec_normal_max <-
  c(spec30_normal_max,
        spec100_normal_max,
        spec200_normal_max,
        spec300_normal_max,
        spec400_normal_max)

spec_data <- 
  as.data.frame(cbind(cCount,
                      spec_raspir_median, 
                      spec_raspir_max,
                      spec_raspir_min, spec_normal_median,
                      spec_normal_max, spec_normal_min))

spec_plot <-
  ggplot(data=spec_data) +
  geom_pointrange(aes(x=cCount, 
                      y=spec_raspir_median, 
                      ymin=spec_raspir_min,
                      ymax=spec_raspir_max), color="red") +
  geom_line(aes(x=cCount, y=spec_raspir_median), color="red", size=1.3, alpha=0.5) +
  geom_pointrange(aes(x=cCount, 
                      y=spec_normal_median,
                      ymin=spec_normal_min,
                      ymax=spec_normal_max),
                  color="black") +
  geom_line(aes(x=cCount, y=spec_normal_median), color="black", size=1.3, alpha=0.5) +
  ylab("  Specificity   ") +
  ylim(-2,102) +
  xlab(" ") +
  theme_pubr(border=TRUE, base_size = set_base_size) +
  theme(axis.text.x = element_blank())

```




```{r}
# False discovery rate
FDR_30_raspir_median = median(stats02_30$FDR_raspir)
FDR_30_raspir_min = min(stats02_30$FDR_raspir)
FDR_30_raspir_max = max(stats02_30$FDR_raspir)
  
FDR_30_normal_median = median(stats02_30$FDR_normal)
FDR_30_normal_min = min(stats02_30$FDR_normal)
FDR_30_normal_max = max(stats02_30$FDR_normal)


FDR_100_raspir_median = median(stats02_100$FDR_raspir)
FDR_100_raspir_min = min(stats02_100$FDR_raspir)
FDR_100_raspir_max = max(stats02_100$FDR_raspir)
  
FDR_100_normal_median = median(stats02_100$FDR_normal)
FDR_100_normal_min = min(stats02_100$FDR_normal)
FDR_100_normal_max = max(stats02_100$FDR_normal)

FDR_200_raspir_median = median(stats02_200$FDR_raspir)
FDR_200_raspir_min = min(stats02_200$FDR_raspir)
FDR_200_raspir_max = max(stats02_200$FDR_raspir)
  
FDR_200_normal_median = median(stats02_200$FDR_normal)
FDR_200_normal_min = min(stats02_200$FDR_normal)
FDR_200_normal_max = max(stats02_200$FDR_normal)

FDR_300_raspir_median = median(stats02_300$FDR_raspir)
FDR_300_raspir_min = min(stats02_300$FDR_raspir)
FDR_300_raspir_max = max(stats02_300$FDR_raspir)
  
FDR_300_normal_median = median(stats02_300$FDR_normal)
FDR_300_normal_min = min(stats02_300$FDR_normal)
FDR_300_normal_max = max(stats02_300$FDR_normal)

FDR_400_raspir_median = median(stats02_400$FDR_raspir)
FDR_400_raspir_min = min(stats02_400$FDR_raspir)
FDR_400_raspir_max = max(stats02_400$FDR_raspir)
  
FDR_400_normal_median = median(stats02_400$FDR_normal)
FDR_400_normal_min = min(stats02_400$FDR_normal)
FDR_400_normal_max = max(stats02_400$FDR_normal)

FDR_raspir_median <-
  c(FDR_30_raspir_median, 
        FDR_100_raspir_median,
        FDR_200_raspir_median,
        FDR_300_raspir_median,
        FDR_400_raspir_median)

FDR_raspir_min <-
  c(FDR_30_raspir_min,
        FDR_100_raspir_min,
        FDR_200_raspir_min,
        FDR_300_raspir_min,
        FDR_400_raspir_min)

FDR_raspir_max <-
  c(FDR_30_raspir_max,
        FDR_100_raspir_max,
        FDR_200_raspir_max,
        FDR_300_raspir_max,
        FDR_400_raspir_max)

FDR_normal_median <-
  c(FDR_30_normal_median, 
        FDR_100_normal_median,
        FDR_200_normal_median,
        FDR_300_normal_median,
        FDR_400_normal_median)

FDR_normal_min <-
  c(FDR_30_normal_min,
        FDR_100_normal_min,
        FDR_200_normal_min,
        FDR_300_normal_min,
        FDR_400_normal_min)

FDR_normal_max <-
  c(FDR_30_normal_max,
        FDR_100_normal_max,
        FDR_200_normal_max,
        FDR_300_normal_max,
        FDR_400_normal_max)

FDR_data <- 
  as.data.frame(cbind(cCount,
                      FDR_raspir_median, 
                      FDR_raspir_max,
                      FDR_raspir_min, FDR_normal_median,
                      FDR_normal_max, FDR_normal_min))

FDR_plot <-
  ggplot(data=FDR_data) +
  geom_pointrange(aes(x=cCount, 
                      y=FDR_raspir_median, 
                      ymin=FDR_raspir_min,
                      ymax=FDR_raspir_max), color="red") +
  geom_line(aes(x=cCount, y=FDR_raspir_median), color="red", size=1.3, alpha=0.5) +
  geom_pointrange(aes(x=cCount, 
                      y=FDR_normal_median,
                      ymin=FDR_normal_min,
                      ymax=FDR_normal_max),
                  color="black") +
  geom_line(aes(x=cCount, y=FDR_normal_median), color="black", size=1.3, alpha=0.5) +
  ylab("False discovery rate    ") +
  ylim(-2,102) +
  xlab("Number of reads (rare species)") +
  theme_pubr(border=TRUE, base_size = set_base_size) 

```


```{r}
# False omission rate
FOR_30_raspir_median = median(stats02_30$FOR_raspir)
FOR_30_raspir_min = min(stats02_30$FOR_raspir)
FOR_30_raspir_max = max(stats02_30$FOR_raspir)
  
FOR_30_normal_median = median(stats02_30$FOR_normal)
FOR_30_normal_min = min(stats02_30$FOR_normal)
FOR_30_normal_max = max(stats02_30$FOR_normal)


FOR_100_raspir_median = median(stats02_100$FOR_raspir)
FOR_100_raspir_min = min(stats02_100$FOR_raspir)
FOR_100_raspir_max = max(stats02_100$FOR_raspir)
  
FOR_100_normal_median = median(stats02_100$FOR_normal)
FOR_100_normal_min = min(stats02_100$FOR_normal)
FOR_100_normal_max = max(stats02_100$FOR_normal)

FOR_200_raspir_median = median(stats02_200$FOR_raspir)
FOR_200_raspir_min = min(stats02_200$FOR_raspir)
FOR_200_raspir_max = max(stats02_200$FOR_raspir)
  
FOR_200_normal_median = median(stats02_200$FOR_normal)
FOR_200_normal_min = min(stats02_200$FOR_normal)
FOR_200_normal_max = max(stats02_200$FOR_normal)

FOR_300_raspir_median = median(stats02_300$FOR_raspir)
FOR_300_raspir_min = min(stats02_300$FOR_raspir)
FOR_300_raspir_max = max(stats02_300$FOR_raspir)
  
FOR_300_normal_median = median(stats02_300$FOR_normal)
FOR_300_normal_min = min(stats02_300$FOR_normal)
FOR_300_normal_max = max(stats02_300$FOR_normal)

FOR_400_raspir_median = median(stats02_400$FOR_raspir)
FOR_400_raspir_min = min(stats02_400$FOR_raspir)
FOR_400_raspir_max = max(stats02_400$FOR_raspir)
  
FOR_400_normal_median = median(stats02_400$FOR_normal)
FOR_400_normal_min = min(stats02_400$FOR_normal)
FOR_400_normal_max = max(stats02_400$FOR_normal)

FOR_raspir_median <-
  c(FOR_30_raspir_median, 
        FOR_100_raspir_median,
        FOR_200_raspir_median,
        FOR_300_raspir_median,
        FOR_400_raspir_median)

FOR_raspir_min <-
  c(FOR_30_raspir_min,
        FOR_100_raspir_min,
        FOR_200_raspir_min,
        FOR_300_raspir_min,
        FOR_400_raspir_min)

FOR_raspir_max <-
  c(FOR_30_raspir_max,
        FOR_100_raspir_max,
        FOR_200_raspir_max,
        FOR_300_raspir_max,
        FOR_400_raspir_max)

FOR_normal_median <-
  c(FOR_30_normal_median, 
        FOR_100_normal_median,
        FOR_200_normal_median,
        FOR_300_normal_median,
        FOR_400_normal_median)

FOR_normal_min <-
  c(FOR_30_normal_min,
        FOR_100_normal_min,
        FOR_200_normal_min,
        FOR_300_normal_min,
        FOR_400_normal_min)

FOR_normal_max <-
  c(FOR_30_normal_max,
        FOR_100_normal_max,
        FOR_200_normal_max,
        FOR_300_normal_max,
        FOR_400_normal_max)

FOR_data <- 
  as.data.frame(cbind(cCount,
                      FOR_raspir_median, 
                      FOR_raspir_max,
                      FOR_raspir_min, FOR_normal_median,
                      FOR_normal_max, FOR_normal_min))

FOR_plot <-
  ggplot(data=FOR_data) +
  geom_pointrange(aes(x=cCount, 
                      y=FOR_raspir_median, 
                      ymin=FOR_raspir_min,
                      ymax=FOR_raspir_max), color="red") +
  geom_line(aes(x=cCount, y=FOR_raspir_median), color="red", size=1.3, alpha=0.5) +
  geom_pointrange(aes(x=cCount, 
                      y=FOR_normal_median,
                      ymin=FOR_normal_min,
                      ymax=FOR_normal_max),
                  color="black") +
  geom_line(aes(x=cCount, y=FOR_normal_median), color="black", size=1.3, alpha=0.5) +
  ylab("False omission rate     ") +
  ylim(-2,102) +
  xlab("Number of reads (rare species)") +
  theme_pubr(border=TRUE, base_size = set_base_size)

```

```{r}
Figure02_arrange <-
  ggarrange(sens_plot, spec_plot,
            FDR_plot, FOR_plot, nrow = 2, ncol = 2,
            labels = c("a", "b", "c", "d"),
            font.label = list(size = 10, color = "black"))

#ggsave("Figure02.pdf",
 #      Figure02_arrange,
  #     device="pdf",
   #    width=5.63,
    #   height = 4.21,
     #  dpi=1200)
```


```{r}
# Statistical comparison
stats02 <- subset(stats02, Count != 500)

# Normality testing
shapiro.test(stats02$Sensitivity_raspir)
shapiro.test(stats02$Sensitivity_normal)
shapiro.test(stats02$Specificity_raspir)
shapiro.test(stats02$Specificity_normal)
shapiro.test(stats02$FDR_raspir)
shapiro.test(stats02$FDR_normal)
shapiro.test(stats02$FOR_raspir)
shapiro.test(stats02$FOR_normal)

# Conclusion: The data has no normal distribution


stats02_raspir <- 
  select(stats02, c(Count, Specificity_raspir, Sensitivity_raspir,
                    FDR_raspir, FOR_raspir))
stats02_raspir$Tool <- "raspir"
colnames(stats02_raspir) <- c("Count", "Specificity", 
                              "Sensitivity", "FDR", "FOR", "Tool")

stats02_normal <- 
  select(stats02, c(Count, Specificity_normal, Sensitivity_normal,
                    FDR_normal, FOR_normal))
stats02_normal$Tool <- "normal"
colnames(stats02_normal) <- c("Count", "Specificity", 
                              "Sensitivity", "FDR", "FOR", "Tool")

stat_compare_df <-
  rbind(stats02_raspir,
        stats02_normal)



# Mann whitney U test
# Specificity
wilcox.test(stat_compare_df$Specificity ~ stat_compare_df$Tool)
wilcoxonR(x = stat_compare_df$Specificity,
          g = stat_compare_df$Tool,
          ci = TRUE)

# Sensitivity
wilcox.test(stat_compare_df$Sensitivity ~ stat_compare_df$Tool)
wilcoxonR(x = stat_compare_df$Sensitivity,
          g = stat_compare_df$Tool,
          ci = TRUE)
# Sensitivity with more than 100 counts for rare species:
stat_compare_df_a <- 
  subset(stat_compare_df, Count > 100)
wilcox.test(stat_compare_df_a$Sensitivity ~ stat_compare_df_a$Tool)
wilcoxonR(x = stat_compare_df_a$Sensitivity,
          g = stat_compare_df_a$Tool,
          ci = TRUE)


# False discovery rate
wilcox.test(stat_compare_df$FDR ~ stat_compare_df$Tool)
wilcoxonR(x = stat_compare_df$FDR,
          g = stat_compare_df$Tool,
          ci = TRUE)


# False omission rate
wilcox.test(stat_compare_df$FOR ~ stat_compare_df$Tool)
wilcoxonR(x = stat_compare_df$FOR,
          g = stat_compare_df$Tool,
          ci = TRUE)
```



```{r}
# The influence of the aligner tool (bwa vs bowtie) on raspir's performance

# Mann-Whitey-U test
# Sensitivity
wilcox.test(stats02$Sensitivity_raspir ~ stats02$Aligner)
wilcoxonR(x = stats02$Sensitivity_raspir,
          g = stats02$Aligner,
          ci = TRUE)

ggplot(stats02, aes(x=Aligner, y=Sensitivity_raspir)) +
  geom_boxplot() +
  geom_jitter(width = 0.1) +
  ylab("Sensitivity of raspir (in %)") +
  theme_pubr(border=TRUE)


# Specificity
wilcox.test(stats02$Specificity_raspir ~ stats02$Aligner)
wilcoxonR(x = stats02$Specificity_raspir,
          g = stats02$Aligner,
          ci = TRUE)

ggplot(stats02, aes(x=Aligner, y=Specificity_raspir)) +
  geom_boxplot() +
  geom_jitter(width = 0.1) +
  ylab("Specificity of raspir (in %)") +
  theme_pubr(border=TRUE)


# FOR
wilcox.test(stats02$FOR_raspir ~ stats02$Aligner)
wilcoxonR(x = stats02$FOR_raspir,
          g = stats02$Aligner,
          ci = TRUE)
ggplot(stats02, aes(x=Aligner, y=FOR_raspir)) +
  geom_boxplot() +
  geom_jitter(width = 0.1) +
  ylab("False omission rate raspir (in %)") +
  theme_pubr(border=TRUE)


# FDR
wilcox.test(stats02$FDR_raspir ~ stats02$Aligner)
wilcoxonR(x = stats02$FDR_raspir,
          g = stats02$Aligner,
          ci = TRUE)
ggplot(stats02, aes(x=Aligner, y=FDR_raspir)) +
  geom_boxplot() +
  geom_jitter(width = 0.1) +
  ylab("False discovery rate of raspir (in %)") +
  theme_pubr(border=TRUE)
```

```{r}
sessionInfo()
```
